sudo: required
services:
- docker
env:
  global:
  - secure: fbH/5IYjo4S0YwahIGpWpI1Em1gglJdtr6T1V+Pfw15iV+RhU1L2FIaC2uJjHG+SGwJuCOvs/06NsQw4tEjvoGZbuLTBTLV+bVsDyfxNQNaqnSC4j5Uvqkoy17HqDYfjqCPJkEu5Wfio1guOTppwfg3EePIjULlX/R6LTrkjHCz6r76Id0M6ZyKoWb3TGySxXock+td2MBxio1qdWL0flZjEr8Yq2DzLjVZsps6SMqeRO4bdcvk2/cfvmpd5PZX3R04mY2JCuF5C26JLhNcP1ma8KQ6sewqGQRgU4jKD7zK6V5EW0WaMIerSfZusCiBaIC8J6rC57Kqni45rfUYtXVhw9UxEmpVYy7WA8TiCZohB/AL/VgAvaEr9M7FYRv8l0bbaykemxj36Op+405eZ0Ia5H0u+obPkjnaVPgkoZEciwirDZNh5BHNFcxm7VvMv0C1w7+jrypf5+nKl4imExHl1MC+LaBahm2wVMJUdEPv9/+1D4LzVgLcotB+1v8PdU/cM6PrCecZqDe/GvokrFhbtWkOKMgqSSJHopvtDU5c2eO4xQx+ipDeb7zSq/TVjY9jy23jqrkKTRv3OW4QNRalKNyEaKXRme27FbWHxHyMaiG6yXV/RvElvAmTrF1l9W+JY0vLU9+sNvKo468IxTkx4bf7w7MZE0mb56Kh5ejo=
  - secure: wmTgWyHxLHjPzK0P+7Cps0YCyPkmvRTVNM/Trc67gVgNse5gLGZC3bMxJY2y13J0OztiMxVXARiDmzBaEuI7bxh4N7Lf9CJa55wmv3H0IaRQN31zMOBmS7yJEXqKq5PMU9I9xVIFreKyS3yks1Hsh7oAfgsgwP72Z8btBoaRn3bG/PjWNlP06V+LfPdtj2IG6fPHPIeheGONPJY6p8xSbW0213eigXd8LSP/SLIIgWcJGceYx40j9skF/DhzXS/KdrIUv6SIHbVS5ii4dvk3h72XF7BLlPJxesmkdX3yYyw+wzc1Gh31P9+hiC2Ct0ttVdenM/7jJjJxwdEjytpx3CnYabo48b5PCPfXBjkwF2bVQFXqDnK57szgoX4dXlqb9viR3VqvvlUXutIE6M3WBHunSGVOFt5eZqpqBxzQc2E7BNZQpJGGrDhxKuIQr52p9p2bkg0/Fhw4Ih6MEkoDyoLTbx4N7RyhIdXpI3qesPN8b2qmigkRIL9kTI0FSvMQXspkPxySi4vdnCVDAmDEzE8iaRqV3h5Xpoww/F1tsilLwgHh66ed7UPexZHBWy97zjJv8WahunGLGjb6ujqdCFTHyhPD5oOJ0wd0rprAAoW1wW+vbYiWcnkKTPjob8qAn7MwJfk0LCV23PkIpptvT99eQT3wi3Pen2a6hxnhUn8=
  - secure: Qz89nIt5h/+hwA7vQ3fvUk/27IbltVdKNgnlQ8xaFrCeGGkpPjr8lI2XFMs0QQMU+69QCdyh34QyxaZUvHHphG2vY0EJZ8N5pP8Oy3a0egapwDGzm0btZof7DtAqMS8QnAN7OGps+IUQoHLoEysoanzj2HUJNql1Bx6SC3q2h6sK+NSH5zTx78cuLPB2S9F2c1ucLtrfkot4HqkNG/Jh3GUfASzzXZNKT/7uYwBQzdpPj+KHwbN9EBhC1b+3+u0NYDZfOLxfXD9/W77JHLtP3uB9OKL6Tr3/p/2a2ftoE4O2dHHtTkvnsbvCPQu/hv46baqotRrJMRacVtDjvZFNatFTTONYdwRuf6OXuBr6V7zhuEQcxq8qUC7gM7/7iFKOXvrQc/AYqXxhpbVpDuMACXU80kwA1GPNafPRh+xs7GIXx1ZJCYfx/fUHK3ozDma+bzXgOeGKTxOsvXs1aSmitizFCyuU0n0gq1ls6CKXtZvKmpxxSBhqGcOT1mja2Ozo7y20RsmC7p2pw9uvCPScG4GLTzORxER2R/hnFP1EVVkurmYrsZHj4hSBh1dknabmHVO5xosZCa7xZ5KTbSMs9RC6cvgWyxJLtdQ42Zd2qsk83x7r8crZfaH/Mecohtdi0lMN0KAphPmW3nlbByngkqdgJOlSU2g2TfnxhjO1TRw=
language: python
python:
- '3.4'
- '3.5'
before_install:
- openssl aes-256-cbc -K $encrypted_78a67e07d999_key -iv $encrypted_78a67e07d999_iv
  -in deploy_key.enc -out deploy_key -d
- echo -e "Host example.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
install:
- pip install -r requirements-dev.txt
script: py.test src
after_success:
- docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
- docker build -t admiral0/kiwibot:latest .
- docker push admiral0/kiwibot:latest
- ssh -i deploy_key deployer@198.211.126.141
